runtime: go
api_version: go1
instance_class: F1
service: task-queue-experiment
automatic_scaling:
  max_concurrent_requests: 50
threadsafe: true

handlers:
- url: /.*
  script: _go_app
  login: admin
